name = "abdomedi-carrier-api"
main = "cloudflare-worker/dist/index.js"
compatibility_date = "2024-03-20"

[vars]
APP_ORIGIN = "https://app.abdomedi.com"
BOSTA_PRODUCTION_BASE_URL = "https://app.bosta.co"
BOSTA_STAGING_BASE_URL = "https://stg-app.bosta.co"
META_VERIFY_TOKEN = "abdomedi_whatsapp_meta_token"
TURBO_BASE_URL = "https://platform.turbo.info"
CLOUDFLARE_ZONE_ID = "b548bd3bc36d71d87cddfa846c54c23e"

[[routes]]
pattern = "api.abdomedi.com/*"
zone_id = "b548bd3bc36d71d87cddfa846c54c23e"
